name: Test app

on:
  workflow_dispatch:

jobs:
  ios-test:
    runs-on: macOS-latest
    steps:      
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: busybeapp/busybe_app
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: app

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - name: test
        working-directory: ./app
        run: make it-test
